name: chatter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  get: ^4.6.5
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.2.2
  uuid: ^3.0.7
  image_picker: ^0.8.8
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  permission_handler: ^10.3.0
  image_cropper: 
  loading_overlay: ^0.3.0
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  zego_uikit_signaling_plugin: ^2.1.8 
  zego_uikit_prebuilt_call: ^3.1.1 
  share_plus: ^6.3.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/audio/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
